Выполненное дз
htmlacademy-javascript/1399877-kekstagram-28 pull request #5
Opened 2023-02-28 19:24 UTC by Shere1-1Khan

2023-03-01 13:21 UTC, NightDiRaven requested changes
По результатам, в целом направление правильно, но нужно генерировать для комментариев тоже массив объектов:

> comments, массив объектов — список комментариев, оставленных другими пользователями к этой фотографии. Количество комментариев к каждой фотографии вы определяете на своё усмотрение. Все комментарии генерируются случайным образом. Пример описания объекта с комментарием:
```js
{
  id: 135,
  avatar: 'img/avatar-6.svg',
  message: 'В целом всё неплохо. Но не всё.',
  name: 'Артём',
}
```

И поправить немного генерацию в целом, чтобы соответствовала заявленной в ТЗ структуре

Если нужна помощь или консультация, свяжитесь со мной в [телеграмме](https://t.me/nightdiraven)

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +const OBJ = [];
В целом, создать заранее объект и сложить туда результат -- это возможный вариант, особенно, учитывая, что модуль может выполниться только один раз. Но лучше все-таки это перенсти внести внутрь результирующей функции (Сейчас это `saveValueIndexObj`)

```suggestion

```

Плюс если это объект (массив), содержимого которого мы меняем, то его мы называем с маленькой буквы, так же в camelCase нотации. В верхнем регистре остается только то, что является изначальными данным, вот как выше `COMMENTS, NAMES, DESCRIPTIONS`

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +const DESCRIPTION = [
Множественное число

```suggestion
const DESCRIPTIONS = [
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +const COMMENTS_ARRAY = [
Аналогично, чтобы все было в едином стиле:
```suggestion
const COMMENTS = [
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +const NAMES_ARRAY = [
Нет необходимости указывать тип данных внутри переменной s на конце и ide уже нам расскажет, что это скорее всего массив или какая-то коллекция:
```suggestion
const NAMES = [

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +  const randomDescriptionIndex = getRandomPositiveInteger(0, DESCRIPTION.length - 1);
В целом все норм, можно оставить и так. Но, если есть желание, можно вынести в новую функцию универсальную по получаению случайного элемента массива, например такую:
```ts
const getRandomArrayElement = (array) => array[getRandomPositiveInteger(0, array.length - 1)];
```

и тогда будет чуть проще доставать случайные данные из массива
```suggestion
  const description = getRandomArrayElement(DESCRIPTIONS);
```

и при добавлении поля в результрующий объект сразу устанавливать это значение:
```ts
return {
    description: description,
    likes: randomCounterLikes,
    comments: COMMENTS_ARRAY[randomCommentsIndex],
    name: NAMES_ARRAY[randomNameIndex],
}
```


или вовсе не создавать изыбточную переменную и сразу записывать значения в поля объекта:
```ts
return {
    description: getRandomArrayElement(DESCRIPTIONS),
    likes: getRandomPositiveInteger(15,200),
   /* Тут оставльные поля*/
}
```

Можно оставить как и сейчас, если так понятнее, но, понять как это можно упростить -- желательно

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +    comments: COMMENTS_ARRAY[randomCommentsIndex],
comments -- должен быть массивом объектов. Нужно, к примеру, вынести их генерацию в отдельную функцию выше, а тут её вызывать
```suggestion
    comments: createComments(),
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +    comments: COMMENTS_ARRAY[randomCommentsIndex],
Сама функция `createComments` идейно последней функции должна собирать массив определенной в константах выше длины `COMMENTS_COUNT` с объектами каждого комментария, типо вот этого:
```ts
const createComments = () => {
  const comments = []
   for(let i = 0; i < COMMENTS_COUNT; i++){
    comments [i] = {
         id: /*тут уникальный id*/,
        avatar: `img/avatar-${getRandomPositiveInteger(0, 6)}.svg`,
        message: getRandomArrayElement(MESSAGES)
       name: getRandomArrayElement(NAMES),
    };
  }
  return comments
}
```

Конечно, можно это ещё разделить на несколько функций или использовать Array.from, например так:
```ts
const createComments = () => Array.from({length: COMMENTS_COUNT}, () => ({
  id: /*тут уникальный id*/,
  avatar: `img/avatar-${getRandomPositiveInteger(0, 6)}.svg`,
  message: getRandomArrayElement(MESSAGES)
  name: getRandomArrayElement(NAMES),
}))
```

Или так:
```ts
const createComment = () => ({
  id: /*тут уникальный id*/,
  avatar: `img/avatar-${getRandomPositiveInteger(0, 6)}.svg`,
  message: getRandomArrayElement(MESSAGES)
  name: getRandomArrayElement(NAMES),
})

const createComments = () => Array.from({length: COMMENTS_COUNT}, createComment)
```

Главное, чтобы было понимание, что у нас будет функция `createComments` которая возвращает массив вот такого вида: 
![image](https://user-images.githubusercontent.com/11852682/222149177-03044cc7-e556-4005-aa8d-6c3c8985e812.png)

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +    name: NAMES_ARRAY[randomNameIndex],
name у комментария, у описания фотография нет такого поля
```suggestion
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +const saveValueIndexObj = () =>{
Лучше переименовать в `createPhotoDescriptions` по аналогии с предыдущей, только предыдущая функция возвращала 1 объект описания фотографии, а эта будет возвращать массив таких описаний.

Да, понятно, в чем была идея изначально определить OBJ  и с помощью вызова этой функции наполнить его. Но  лучше отойти от этого и сделать функцию, внутри которой и создается искомый массив.
```suggestion
const createPhotoDescriptions= () =>{
  const photos = [];
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +    name: NAMES_ARRAY[randomNameIndex],
Так же можно сразу сюда добавить id и url
```suggestion
    id: randomIdNumber(),
    url: `photo/${randomUrlNumber()}.jpg`
```
Не вижи практичесго смысла делать это после: мы сразу создаем объект описания со всеми полями, для чего эти два добавлять потом?

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +    OBJ[i] = createObj();
```suggestion
photos[i] = createPhotoDescription();
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +};
```suggestion
 return photos;
};
```

2023-03-01 13:21 UTC, NightDiRaven commented on js/main.js
> +saveValueIndexObj();
Если все правильно, у нас в консоле будет массив с 25 объектам у каждого из которых есть свойство comments в нутри каждого из которых тоже массив с объектамм комментариев...
```suggestion
console.log(createPhotoDescriptions());
```

2023-03-07 16:45 UTC, NightDiRaven requested changes
Почти все норм, только нужен массив комментариев, вместо объекта, остальное все из прошлых правок учтено

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +  const OBJ = [];
Это изменяемый объект, нужно в camelCase нотации, например `photos` или `descriptions`, в крайнем случае можно оставить и `objects` главное во множественном числе, это же массив объектов будет

```suggestion
  const photos = [];
```

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +const createObj = () =>{
Поскольку ты ниже переименуешь `OBJ` в какое-то множественное число, то и тут соответственно нужно переименовать в одно из `createPhotos` / `createDescriptions` / `createObjects`

```suggestion
const createPhotos= () =>{
```

P.S. createObjects лучше не использовать, это слишком абстрактно, нужно понимать что мы создаем: не какие-то объект а конкретные объекты фотографий

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +    OBJ[i].name = getRandomArrayElement(NAMES);
Имени у фотки вообще нет по ТЗ, нужно убрать, оно остается внутри комментариев.
```suggestion

```

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +const createComments = () =>({
Почти, только есть несколько нюансов: сейчас ты создаешь 1 объект комментари я и отдаешь его, а нужно массив комментариев отдавать, например так:
```ts
// Количество комментариев в самый верх кода добавить
const COMMENTS_COUNT = 3;

// Чтобы id у комментариев не повторялись, создаем для них тоже генератор:
const getCommentId = createIdGenerator();

const createComments = () => Array.from({length: COMMENTS_COUNT}, () =>({
  id: getCommentId(), // Получаем уникальные id для каждого объекта
  avatar: `img/avatar-${getRandomPositiveInteger(0, 6)}.svg`,
  message: getRandomArrayElement(COMMENTS),
  name: getRandomArrayElement(NAMES),
}));
```

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +  const randomIdNumber = createIdGenerator();
В этой константе лежит функция, нужно называть с глаголом по критериям, т.е. например так:
```suggestion
  const getPhotoId = createIdGenerator();
```

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +  const randomUrlNumber = createIdGenerator();
Аналогично, тут внутри функция, нужен глагол, например `получитьНомерФото`
```suggestion
  const getPhotoNumber= createIdGenerator();
```

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +    OBJ[i].id = randomIdNumber();
```suggestion
    OBJ[i].id = getPhotoId();
```

2023-03-07 16:45 UTC, NightDiRaven commented on js/main.js
> +    OBJ[i].url = `photo/${randomUrlNumber()}.jpg`;
```suggestion
    OBJ[i].url = `photo/${getPhotoNumber()}.jpg`;
```

2023-03-08 14:31 UTC, Shere1-1Khan commented on js/main.js
> +const createComments = () =>({
+

2023-03-08 14:32 UTC, Shere1-1Khan commented on js/main.js
> +const createObj = () =>{
+

2023-03-08 14:33 UTC, Shere1-1Khan commented on js/main.js
> +  const randomIdNumber = createIdGenerator();
+

2023-03-08 14:33 UTC, Shere1-1Khan commented on js/main.js
> +  const randomUrlNumber = createIdGenerator();
+

2023-03-08 14:33 UTC, Shere1-1Khan commented on js/main.js
> +  const OBJ = [];
+

2023-03-08 17:52 UTC, NightDiRaven approved these changes

2023-03-08 17:53 UTC, merged