Отрисуй меня полностью
htmlacademy-javascript/1399877-kekstagram-28 pull request #7
Opened 2023-03-13 20:20 UTC by Shere1-1Khan

---
:mortar_board: [Отрисуй меня полностью](https://up.htmlacademy.ru/javascript/28/user/1399877/tasks/12)

2023-03-14 11:51 UTC, NightDiRaven requested changes
Посмотри комментарии, если что-то непонятно -- пиши

2023-03-14 11:51 UTC, NightDiRaven commented on js/main.js
> +import './mockPhotos.js';
Идея main.js в целом такая: ты импортируешь интерфейс (одну или несколько функций) из основных модулей, например createPhotos
```suggestion
import {createPhotos} './mockPhotos.js';
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/main.js
> +import './renderingPicture.js';
А из этого модуля мы импортируем функцию `renderPhotos` т.е. первый модуль выше создает данные (`createPhotos`)
а этот модуль их отрисовывает, но только с помощью нашей функции `renderPhotos`
```suggestion
import {renderPhotos}  from './renderingPicture.js';
```

Т.е. сами по себе модули не делают никаких сайд-эффектов (т.е. они не должны там менять ничего в DOM сами по себе, удалять или добавлять что-то, только инициализоваться и предоставлять набор функций, с помощью которых мы сможем запустить их функционал (например создание картинок или например отрисовывание их) только тогда когда нам нужно, а не в момент импорта)

Важно понимать, что импорт это просто подключение, всегда нужно выносить управление модулем из него с помощью вот экспорта таких вот функций.

Ещё раз вот расскажу: модуль это просто набор каких-то функций, которые связаны предметно, как у тебя сейчас 2 основных модуля это `mockPhotos.js` и `renderingPictures.js`. Их подключение не должно делать ничего, как будто ты и не подключал их вовсе. Но, каждый из этих модулей экспортирует свои функции, с помошью которых ты сможешь запустить механизм их выполнения, в первом модуле `mockPhotos.js`у тебя функция `createPhotos` в идеале ты можешь ещё вызвать 10 раз и получить не 25 картинок, а 250, т.е. в идеале каждое выполнение функции должно давать одинаковый логический результ 25 новых катринок. (Сейчас это не совсем так, но не будем усложнять, главное чтобы ты понял идею модулей)

а второй модуль`renderingPictures.js` у тебя тоже ничего не должен делать до момента вызова некой функции, например `renderPhotos` которая будет принимать массив данных кратинок и отрисовывать их. При этом не важно сколько будет картинок в массиве, 10, 20, 30, она просто принимает данные и отрисовывает. Можно отрисовать 10 раз вызвав по две или сразу 25 за раз, идея только в том, что модуль отрисовки предоставляет такую возможность.

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +import {createPhotos} from './mockPhotos.js';
```suggestion

```

Нужно убрать отсюда, чтобы не связывать модуль генерации и отрисовки напрямую. нужно их связать например через main.js

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +const dataCreatePicture = createPhotos();
перенести получение в main.js
```suggestion

```

2023-03-14 11:51 UTC, NightDiRaven commented on js/main.js
> +
И тут же в этом файле main.js теперь мы выполняем логику "основного потока" нашего приложения
```suggestion
// Получаем данные
const photos = createPhotos();

// И их отрисовываем
renderPhotos(photos);
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +const SAMPLE = document.querySelector('#picture').content.cloneNode(true);
В camelCase. Константы пишутся в верхнем регистре только если эти данные не меняются ДО выполнения кода. А тут ты вычисляешь значение и динамически его присваивашь во время первого выполнения. Да, ссылка на объект не будет меняться, это константа, но это не предопределенная константа, это не данные "извне" а результат выполнения.
```suggestion
const samplePicture = document.querySelector('#picture').content.cloneNode(true);
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +const PICTURES = document.querySelector('.pictures');
В camelCase. Типо такого, можно и просто `pictures` если тебе точно понятно что это такое
```suggestion
const picturesContainer = document.querySelector('.pictures');
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +const fragment = document.createDocumentFragment();
Перенести отсюда создание фрагмента в функцию отрисовки
```suggestion

```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  randomPhoto.srс = data.url;
**Ошибка** символ "c" на русском языке, надо на английском "src", чтобы такого не было лучше всега пиши не только "c", а целиком "src" или любое другое слово: никогда не исправляй только одну С/с, всегда можешь ошибиться, если в ide не настроена подсветка "ASCII и non-ASCII" символов
```suggestion
  randomPhoto.src= data.url;
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +const createPictures = (data, sample) =>{
Конкретно эта функция у тебя создает 1 плитку фотографии/картинки, не нужно множественное число.
И любая функция в js замыкание -- она видет все определенные переменные на момент определения, нет в данном случае необходимости добавлять sample в качестве аргумента: она же определена выше, значит внутри этой функции будет доступ к этой внешней переменной
```suggestion
const createPicture = (data) =>{
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  const sampleClone = sample.cloneNode(true);
Мы просто можем взять переменную samplePicture "снаружи" этой функции
```suggestion
  const sampleClone = samplePicture.cloneNode(true);
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  likes.textContent = data.likes;
Можно сделать в 1 строчку, сразу достать и установить, но можно оставить как есть
```suggestion
  sampleClone.querySelector('.picture__likes').textContent = data.likes;
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  comments.textContent = data.comments.length;
Аналогично, но можно и определить переменную избыточную, вроде не базовый критерий
```suggestion
  sampleClone.querySelector('.picture__comments').textContent = data.comments.length;
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  fragment.appendChild(sampleClone);
Итак, в этой функции мы сколнировали элемент, заполнили его данными, но давай не добавлять этот элемент в фрагмент, а вернем наш элемент из этой функции, сделав её попроще (в логическом плане):
```suggestion
  return sampleClone;
```
Это даст нам больше гибкости в дальнейшем: когда функция (любая) выполняет одну и только одну задачу -- это идеальный случай, к сожалению, не всегда это удается сделать, но тут есть такая возможность: наша функция `createPicture` получает данные и возвращает нам DOM элемент заполненный этими данными. Теперь мы можем её использовать где угодно и как угодно для этой задачи в рамках нашего проекта.

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  PICTURES.appendChild(fragment);
Так же удаляем и отрисовку
```suggestion

```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +for(let i = 0; i < dataCreatePicture.length ; i++){
Как и было сказано выше, не нужно, чтобы модуль при первом же выполнении что-то рисовал или делал что-то кроме инициализации (под инициализацией в данном случае можно понимать вот определение всех констант и функций)

Т.е. мы должны завернуть нашу отрисовку тоже в функцию, назавем её `renderPhotos` (Можешь назвать `renderPictures` по аналогии, главное **сделай везде одинаково во всех модулях**)
```suggestion
// Функция у нас принимает массив данных фотографий
const renderPhotos = (photos) => {
 // создается пустой фрагмент
  const fragment = document.createDocumentFragment();

  for (let i = 0; i < photos.length; i++) {
// для каждой фотографии создается элемент-клон и этот элемент добавляется в наш пустой фрагмент
    fragment.appendChild(createPicture(photos[i]));
  }
  // под конец наш заполненный фотографиями-элементами фрагмент один раз добавляется в наш html
  picturesContainer.appendChild(fragment);
}
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +for(let i = 0; i < dataCreatePicture.length ; i++){
Ну и попробуй не писать `for` и использовать `forEach` например так:
```suggestion
const renderPhotos = (photos) => {
  const fragment = document.createDocumentFragment();

  photos.forEach((photo) => fragment.appendChild(createPicture(photo)));

  picturesContainer.appendChild(fragment);
};
```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +  createPictures(dataCreatePicture[i],SAMPLE);
```suggestion

```

2023-03-14 11:51 UTC, NightDiRaven commented on js/renderingPicture.js
> +export {dataCreatePicture};
```suggestion
export {renderPhotos};
```

2023-03-14 18:56 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +import {createPhotos} from './mockPhotos.js';
+

2023-03-14 18:56 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +const dataCreatePicture = createPhotos();
+

2023-03-14 18:56 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +const SAMPLE = document.querySelector('#picture').content.cloneNode(true);
+

2023-03-14 18:57 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +const PICTURES = document.querySelector('.pictures');
+

2023-03-14 18:57 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +const fragment = document.createDocumentFragment();
+

2023-03-14 18:57 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +const createPictures = (data, sample) =>{
+

2023-03-14 18:57 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +  const sampleClone = sample.cloneNode(true);
+

2023-03-14 18:57 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +  randomPhoto.srс = data.url;
+

2023-03-14 18:57 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +  likes.textContent = data.likes;
+

2023-03-14 18:58 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +  comments.textContent = data.comments.length;
+

2023-03-14 19:00 UTC, Shere1-1Khan commented on js/renderingPicture.js
> +for(let i = 0; i < dataCreatePicture.length ; i++){
+

2023-03-15 12:13 UTC, NightDiRaven approved these changes
Можешь и `renderingPuctures.js` переименовать в `renderPhotos.js` тогда уж чтобы у тебя все в едином стиле называлось

2023-03-15 12:13 UTC, merged