module8-task1
htmlacademy-javascript/1399877-kekstagram-28 pull request #8
Opened 2023-03-18 18:50 UTC by Shere1-1Khan

2023-03-19 17:21 UTC, NightDiRaven requested changes
В целом твой код рабочий, но есть нюансы, ты не сможешь его в таком виде в дальнейшем использовать для расширения. Например чтобы выполнить задание с фильтрацией, тебе придется это в любом случае переписать. Поэтому я постарался оставить твой вариант с делегированием, но перетасовал немного все что ты написал в другие методы и порядок выпонения: теперь модуль галерии независим и работает сам по себе, мы просто устанавливаем в него актуальный список фотографий через `setPhotos`

Если что-то непонятно по коду, то пиши...

2023-03-19 17:21 UTC, NightDiRaven commented on js/main.js
> +import { addHandler } from './popupGallery.js';
Предлагаю изменить название метода, на какое-то такое. Т.е. идея, насколько я понимаю, будет такая: у нас механизм работы галереи вообще независим от фотографий. Единственная связь с ними через данные, которые мы можем "установить" в нашу галерею. 
```suggestion
import { setPhotos} from './popupGallery.js';
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/main.js
> +addHandler(photos);
`addHandler` не совсем корректно, поскольку идея не в том, чтобы установить обработчик, он уже там установлен и работает, а в том, чтобы передать в модуль галереи данные наших фотографий.
Возможно, даже в будущем мы перенесем вызов этого модуля внутрь renderPhotos, но можно и нет, но на данный момент это вот как-то так:
```suggestion
setPhotos(photos);
```
Мы передаем внуть нашей галереи текущие "актуальные" данные, мы можем изменить фотографии и установить новый массив и галерея должна так же функционировать.

2023-03-19 17:21 UTC, NightDiRaven commented on js/mockPhotos.js
>  const createComments = () => Array.from({length: COMMENTS_COUNT},() => ({
Добавим случайное количество комментариев от 1 до COMMENTS_COUNT, 1 тоже лучше вынести, как минимальное количество комментариев. Это для того, чтобы было лучше виден результат, иначе везде по 3 комментария и непонятно, всё ли у нас правильно работает
```suggestion
const createComments = () => Array.from({length: getRandomPositiveInteger(1, COMMENTS_COUNT)},() => ({

```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const commentsList = displayingWindow.querySelectorAll('.social__comments li');
Нам нужен контейнер в который мы будем помещать все наши комментарии, возьмем переменную `commentsList` для этого и просто туда достанем наш контейнер.
Так же мы возьмем один комментарий `.social__comment` и склонируем его (Это просто 1 комментарий из DOM но мы его склонировали и теперь будем использовать в качестве "шаблона" для создания каждого комментария)
```suggestion
const commentsList = displayingWindow.querySelector('.social__comments');
const commentTemplate = displayingWindow.querySelector('.social__comment').cloneNode(true);
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +
Обозначим "глобальную" переменную этого модуля с актуальным набором данных фотографий.
```suggestion

let photos = [];

```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const addClass = ()=>{
Пока разнесем вообще эту функцию и уберём её. К слову название addClass не совсем рассказывает что она делает. Нужно чот-то вроде "установитьКлассыПриОткрытии"

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const closePopup = ()=>{
Если `showPopup` то лучше назвать `hidePopup`  show/hide, close/open
```suggestion
const hidePopup = (e) => {
  if (e.key && e.key !== 'Escape') {
    return;
  }
  e.preventDefault();
  displayingWindow.classList.add('hidden');
  closeBigPhoto.removeEventListener('click', hidePopup);
  document.removeEventListener('keydown', hidePopup);
  document.body.classList.remove('modal-open');
};
```
И с описанием, возможно, придется назвать и hidePopupHandler, но не суть
```ts
const hidePopup = (e) => {
 Проверяем, был ли ивент вызван нажатием на кнопку и если был и это не esc, то ничего не делаем
  if (e.key && e.key !== 'Escape') {
    return;
  }
  // Отменяем стандарное поведение
  e.preventDefault();
  // Скрываем попап
  displayingWindow.classList.add('hidden');
  // Убераем ивент на кнопку 
  closeBigPhoto.removeEventListener('click', hidePopup);
  // Убираем ивент на закрытие по esc
  document.removeEventListener('keydown', hidePopup);
  // Убираем класс открытого попапа у body 
  document.body.classList.remove('modal-open');
};
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const closePopupKey = ()=>{
Тут получается дублирование когда по скрытию, лучше так не делать, вынести в отдельный обработчик для закрытия по esc можно, но это будет иначе, можно пока удалить вообще

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const addComments = (indexArray) =>{
Твой же код, но тут вся логика на данный момент связанная с отрисовкой комментариев
```suggestion
const addComments = (comments) => {
  // Скрываем по заданию пока счетчики (в следующих будем с ними работать)
  displayingWindow.querySelector('.social__comment-count').classList.add('hidden');
  displayingWindow.querySelector('.comments-loader').classList.add('hidden');

  // Удаляем все комментарии (очищаем весь блок с комментариями)
  commentsList.innerHTML = '';
  // Устанавливаем количество комментариев в нужный блок
  commentCount.textContent = comments.length;
  
  // Создаем фрагмент для вставки в него комментариев
  const commentsFragment = document.createDocumentFragment();

  // По аналогии с фотками, как мы делали, создаем каждоый комментарий и добавляем его во фрагмент
  comments.forEach((comment) => {
    const commentClone = commentTemplate.cloneNode(true);
    const img = commentClone.querySelector('img');
    img.src = comment.avatar;
    img.alt = comment.name;
    commentClone.querySelector('p').textContent = comment.message;
    commentsFragment.append(commentClone);
  });

  // отрисовываем фрагмент в нашем блоке с комментариями
  commentsList.append(commentsFragment);
};
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const appendData = (array,id) =>{
Устанавливаем из данных одной фотографии все в наш попап
```suggestion
const setPhotoData = (photo) => {
  bigPicture.src = photo.url;
  likesCounter.textContent = photo.likes;
  descriptionPhoto.textContent = photo.description;
  addComments(photo.comments);
};
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const addHandler = (data) =>{
Уставаливаем актуальные данные в наш "глобальный" массив-переменную модуля с фотками
```suggestion
const setPhotos = (data) => {
  photos = data;
};
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +export { addHandler };
Инициализируем галерею, добавив ивент на весь блок и возвращаем метод по наполнения нашего массива с данными
```suggestion

picturesContainer.addEventListener('click', showPopup);

export {setPhotos};
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/popupGallery.js
> +const showPopup = ()=>{
`addComments` и `setPhotoData` нужно перенести выше этой функции
```suggestion
const showPopup = (event) => {
  event.preventDefault();
  const photoId = parseInt(event.target.closest('[data-id]')?.dataset.id, 10);

  if (!photoId) {
    return;
  }

  const photoData = photos.find((photo) => photo.id === photoId);
  if (!photoData) {
    return;
  }
  
  setPhotoData(photoData);

  displayingWindow.classList.remove('hidden');
  closeBigPhoto.addEventListener('click', hidePopup);
  document.addEventListener('keydown', hidePopup);
  document.body.classList.add('modal-open');
};
```

2023-03-19 17:21 UTC, NightDiRaven commented on js/renderingPicture.js
> +  randomPhoto.dataset.indexId = data.id;
я убрал index из index-id но если хочешь оставь, ну и в методе верни тоже
```suggestion
  randomPhoto.dataset.id= data.id;
```

2023-03-19 17:26 UTC, Shere1-1Khan commented on js/popupGallery.js
> +const commentsList = displayingWindow.querySelectorAll('.social__comments li');
+

2023-03-19 17:27 UTC, Shere1-1Khan commented on js/popupGallery.js
> +
+

2023-03-19 17:55 UTC, Shere1-1Khan commented on js/mockPhotos.js
>  const createComments = () => Array.from({length: COMMENTS_COUNT},() => ({
+

2023-03-19 18:23 UTC, Shere1-1Khan commented on js/mockPhotos.js
>  const createComments = () => Array.from({length: COMMENTS_COUNT},() => ({
Тут я решил попробовать использовать рандомное количество комментариев и отказаться от использования  переменной COMMENTS_COUNT.

2023-03-21 18:57 UTC, merged

2023-03-21 18:58 UTC, NightDiRaven commented on js/popupGallery.js
> +  commentLoader.classList.remove('hidden');
Вот эта строчка не нужна, ты скрываешь и отображаешь лоадер уже в логике loadNext, дублирование, но и ни на что не повлияет